#SPDX-License-Identifier: MIT-0
---
# tasks file for CUR3direct_nginx_conf
- name: Include nginx role
  ansible.builtin.include_role:
    name: CUR3direct_nginx
  
- name: Include certbot role, if tls is true
  ansible.builtin.include_role:
    name: CUR3direct_certbot
  when: tls

- name: Srv Conf 
  ansible.builtin.template:
    src: "{{ conf_template_name }}"
    dest: /etc/nginx/sites-available/{{ server_num }}-{{ srv_name }}.conf
    owner: root
    group: root
    mode: '0640'

- name: Activate Conf
  vars:
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ server_num }}-{{ srv_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ server_num }}-{{ srv_name }}.conf
    state: link
  notify: Restart Nginx