---
- name: Provision Redirect server
  hosts: CUR3direct_srv
  become: true
  become_method: sudo
  vars:
      dn_source: helipad.cloud
      vps_host: linode
      cert_provider: Snapd_Linode
      certbot_admin_email: cur3@bobot.lol
      server_num: "00"
      nginx_client_max_body_size: "1M"
  roles:
#   - CUR3directUfw
    - role: CUR3direct_nginx_conf
      conf_template_name: nginx-redirect.conf.j2
      srv_name: helipad.cloud
      dn_destination: https://podcastindex.org/
      redirect_code: 301
      tls: true
      ipv6: true
      server_num: "33"
    - role: CUR3direct_nginx_conf
      conf_template_name: nginx-reverse-proxy.conf.j2
      srv_name: serf00
      tls: true
      ipv6: true
      srv_subdomain: serf00
      srv_upstream: localhost
      srv_upstream_port: 2342
      server_num: "01"
