---
# tasks file for CUR3direct_redirect

- name: Include certbot role, if tls is true
  ansible.builtin.include_role:
    name: CUR3direct_certbot
  when: tls

- name: Template redirect
  vars:
    
  ansible.builtin.template:
    src: nginx-{{ server_num }}-redirect.conf.j2
    dest: /etc/nginx/sites-available/{{ server_num }}-{{ dn_source }}
    owner: root
    group: root
    mode: '0640'
  notify: Restart Nginx
- name: Activate redirect
  vars:
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ server_num }}-{{ dn_source }}
    dest: /etc/nginx/sites-enabled/{{ server_num }}-{{ dn_source }}
    state: link
  notify: Restart Nginx
