---
# tasks file for CUR3direct_certbot

- name: Include cert_provider Snapd DigitalOcean
  ansible.builtin.include_tasks: setup-Snapd-certbot-digitalOcean.yaml
  when: cert_provider == 'Snapd_DigitalOcean'

- name: Create cert via certbot digital ocean dns
  ansible.builtin.command:
    cmd: >
      {{ certbot }} certonly
      --email '{{ certbot_admin_email }}'
      --dns-digitalocean --dns-digitalocean-credentials {{ secrets_ini }}
      --noninteractive --agree-tos
      -d {{ dn_source }}
    creates: /etc/letsencrypt/live/{{ dn_source }}/cert.pem

- name: Enable renew 30 days before exipry
  ansible.builtin.lineinfile:
    dest: /etc/letsencrypt/renewal/{{ dn_source }}.conf
    regexp: '^# renew_before_expiry = 30 days'
    line: "renew_before_expiry = 30 days"
    state: present
    backup: true
  notify:
    - Restart certbot

- name: Copy nginx reload post hook
  ansible.builtin.copy:
    src: etc/letsencrypt/renewal-hooks/post/01_nginx-reload-post-hook.sh
    dest: /etc/letsencrypt/renewal-hooks/post/01_nginx-reload-post-hook.sh
    owner: root
    group: root
    mode: '0644'
