---

- name: Install certbot
  community.general.snap:
    name: certbot
    classic: true
    options:
      - trust-plugin-with-root=ok

- name: Install certbot-dns-linode
  community.general.snap:
    name: certbot-dns-linode

- name: Create certbot secrets dir
  ansible.builtin.file:
    path: /root/.secrets/certbot/
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Template linode api_key ini
  ansible.builtin.template:
    src: secret-certbot-linode.ini.j2
    dest: /root/.secrets/certbot/linode.ini
    owner: root
    group: root
    mode: '0600'

- name: Include snapd vars
  ansible.builtin.include_vars:
    snapd.yml

- name: Create cert via certbot linode dns
  ansible.builtin.command:
    cmd: >
      {{ certbot }} certonly
      -m '{{ certbot_admin_email }}'
      -n --agree-tos
      --dns-linode
      --dns-linode-credentials ~/.secrets/certbot/linode.ini
      --dns-linode-propagation-seconds 120
      -d {{ dn_source }}
    creates: /etc/letsencrypt/live/{{ dn_source }}/cert.pem
